// Code generated by Kitex v0.10.3. DO NOT EDIT.

package etcdenvservice

import (
	"context"
	autoenv "github.com/Solituderr/autoenv/kitex_gen/chatgpt/model/autoenv"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetEtcdEnv(ctx context.Context, req *autoenv.GetEtcdEnvReq, callOptions ...callopt.Option) (r *autoenv.GetEtcdEnvResp, err error)
	SetEtcdEnv(ctx context.Context, req *autoenv.SetEtcdEnvReq, callOptions ...callopt.Option) (r *autoenv.SetEtcdEnvResp, err error)
	CronJob(ctx context.Context, req *autoenv.CronJobReq, callOptions ...callopt.Option) (r *autoenv.CronJobResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kEtcdEnvServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEtcdEnvServiceClient struct {
	*kClient
}

func (p *kEtcdEnvServiceClient) GetEtcdEnv(ctx context.Context, req *autoenv.GetEtcdEnvReq, callOptions ...callopt.Option) (r *autoenv.GetEtcdEnvResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetEtcdEnv(ctx, req)
}

func (p *kEtcdEnvServiceClient) SetEtcdEnv(ctx context.Context, req *autoenv.SetEtcdEnvReq, callOptions ...callopt.Option) (r *autoenv.SetEtcdEnvResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetEtcdEnv(ctx, req)
}

func (p *kEtcdEnvServiceClient) CronJob(ctx context.Context, req *autoenv.CronJobReq, callOptions ...callopt.Option) (r *autoenv.CronJobResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CronJob(ctx, req)
}
