// Code generated by Kitex v0.10.3. DO NOT EDIT.

package etcdenvservice

import (
	autoenv "github.com/Solituderr/autoenv/kitex_gen/chatgpt/model/autoenv"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler autoenv.EtcdEnvService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
