// Code generated by Kitex v0.10.3. DO NOT EDIT.
package etcdenvservice

import (
	autoenv "github.com/Solituderr/autoenv/kitex_gen/chatgpt/model/autoenv"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler autoenv.EtcdEnvService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler autoenv.EtcdEnvService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
